engines:
  pep8:
    enabled: true
    checks:
      E501:
        enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
      - python:

ratings:
  paths:
  - testcube/**

exclude_paths:
- "*.*"
- "docs/**"
- "scripts/**"
- "**/tests/**"
- "**/migrations/**"
- "**/static/libs/**"
- "**/static/docs/**"
- "**/static/images/**"
